// This is autogenerated file, don't try to edit it manually
/* eslint-disable */
import { Palette } from './types';

export const light: Palette = {
    type: 'light',
    Background: {
        blackout: 'rgba(0, 0, 0, 0.4)',
        main: '#ffffff',
        secondary: '#eef3ff',
        tertiary: '#333f48'
    },
    Button: {
        contained: {
            critical: {
                enabled: '#f0161c',
                hover: '#f34549',
                press: '#d91419'
            },
            primary: {
                disabled: 'rgba(0, 0, 0, 0.16)',
                enabled: '#21ba72',
                hover: '#44d370',
                press: '#209f6d'
            },
            secondary: {
                enabled: '#333f48',
                hover: '#4e5961',
                press: '#182329'
            }
        },
        outline: {
            critical: {
                bgHover: '#f0161c',
                bgPress: '#d91419',
                strokeEnabled: '#f0161c'
            },
            primary: {
                bgPress: '#209f6d',
                enabled: '#21ba72',
                hover: '#21ba72',
                strokeDisabled: 'rgba(0, 0, 0, 0.16)'
            },
            secondary: {
                bgHover: 'rgba(0, 0, 0, 0.04)',
                bgPress: 'rgba(0, 0, 0, 0.08)',
                strokeEnabled: 'rgba(0, 0, 0, 0.24)'
            }
        },
        text: {
            critical: {
                bgHover: 'rgba(252, 208, 210, 0.32)',
                bgPress: 'rgba(252, 208, 210, 0.56)'
            },
            primary: {
                bgHover: 'rgba(198, 244, 198, 0.32)',
                bgPress: 'rgba(198, 244, 198, 0.56)'
            },
            secondary: {
                bgHover: 'rgba(0, 0, 0, 0.04)',
                bgPress: 'rgba(0, 0, 0, 0.08)'
            }
        }
    },
    Checkbox: {
        active: {
            bg: '#21ba72',
            bgHover: '#44d370',
            icon: '#ffffff'
        },
        critical: {
            bg: '#d91419',
            stroke: '#d91419'
        },
        disabled: {
            bg: 'rgba(0, 0, 0, 0.16)',
            icon: '#ffffff'
        },
        enabled: {
            bg: '#ffffff',
            iconHover: 'rgba(0, 0, 0, 0.12)',
            stroke: 'rgba(0, 0, 0, 0.24)',
            strokeHover: 'rgba(0, 0, 0, 0.32)'
        }
    },
    ContainerState: {
        focus: '#21ba72',
        focus2: 'rgba(0, 0, 0, 0.72)',
        focus3: 'rgba(255, 255, 255, 0.56)',
        hover: 'rgba(0, 0, 0, 0.04)',
        press: 'rgba(0, 0, 0, 0.08)'
    },
    Datepicker: {
        rangeActive: '#21ba72',
        rangeFull: 'rgba(33, 186, 114, 0.16)',
        rangeHover: 'rgba(0, 0, 0, 0.16)',
        rangeIn: 'linear-gradient(90deg, rgba(32, 186, 114, 0) 0%, rgba(32, 186, 114, 0.16) 50%)',
        rangeOut: 'linear-gradient(90deg, rgba(33, 186, 114, 0.16) 50%, rgba(33, 186, 114, 0) 100%)',
        strokeHover: 'rgba(0, 0, 0, 0.12)'
    },
    Divider: {
        main: 'rgba(0, 0, 0, 0.16)',
        mainInverse: 'rgba(255, 255, 255, 0.24)',
        secondary: 'rgba(0, 0, 0, 0.08)',
        secondaryInverse: 'rgba(255, 255, 255, 0.16)'
    },
    FileUploader: {
        dropzone: {
            strokeDisabled: 'rgba(0, 0, 0, 0.16)',
            strokeEnabled: 'rgba(0, 0, 0, 0.24)',
            strokeError: '#e50b30',
            strokeHover: 'rgba(0, 0, 0, 0.4)'
        },
        file: {
            bgEnabled: 'rgba(0, 0, 0, 0.04)',
            bgError: 'rgba(229, 11, 48, 0.08)'
        }
    },
    HintTooltip: {
        bgHint: 'rgba(0, 0, 0, 0.72)',
        bgTooltip: 'rgba(0, 0, 0, 0.72)'
    },
    Icon: {
        brand: '#21ba72',
        critical: '#d91419',
        main: '#000000',
        mainInverse: '#ffffff',
        secondary: 'rgba(0, 0, 0, 0.56)',
        secondaryInverse: 'rgba(255, 255, 255, 0.56)',
        success: '#11be1c',
        tertiary: 'rgba(0, 0, 0, 0.4)',
        tertiaryInverse: 'rgba(255, 255, 255, 0.4)',
        warning: '#eb8900'
    },
    LabelTag: {
        color1: {
            main: '#0087cd',
            secondary: 'rgba(0, 135, 205, 0.36)'
        },
        color2: {
            main: '#333f48',
            secondary: 'rgba(51, 63, 72, 0.36)'
        },
        critical: {
            main: '#d91419',
            secondary: 'rgba(217, 20, 25, 0.36)'
        },
        warning: {
            main: '#eb8900',
            secondary: 'rgba(235, 137, 0, 0.36)'
        }
    },
    RadioButton: {
        active: {
            bg: '#21ba72'
        },
        critical: {
            bg: '#d91419'
        },
        enabled: {
            bg: '#ffffff',
            stroke: 'rgba(0, 0, 0, 0.24)'
        }
    },
    Shadow: {
        black12: 'rgba(0, 0, 0, 0.12)',
        black4: 'rgba(0, 0, 0, 0.04)',
        black8: 'rgba(0, 0, 0, 0.08)'
    },
    Snackbar: {
        bg1: {
            critical: 'radial-gradient(35.0% 100.0% at -0.0% 0.0%, rgba(250, 220, 225, 1) 0%, rgba(255, 255, 255, 1) 100%)',
            default: '#ffffff',
            success: 'radial-gradient(35.0% 100.0% at 0.0% 0.0%, rgba(230, 250, 220, 1) 0%, rgba(255, 255, 255, 1) 100%)',
            warning: 'radial-gradient(35.0% 100.0% at 0.0% 0.0%, rgba(250, 245, 220, 1) 0%, rgba(255, 255, 255, 1) 100%)'
        },
        bg2: {
            critical: 'radial-gradient(0.0% -0.0% at -0.0% 50.0%, rgba(250, 230, 233, 1) 0%, rgba(255, 255, 255, 1) 100%)',
            default: '#ffffff',
            success: 'radial-gradient(0.0% -0.0% at -0.0% 50.0%, rgba(230, 250, 220, 1) 0%, rgba(255, 255, 255, 1) 100%)',
            warning: 'radial-gradient(0.0% -0.0% at -0.0% 50.0%, rgba(250, 245, 220, 1) 0%, rgba(255, 255, 255, 1) 100%)'
        }
    },
    Switcher: {
        active: {
            bg: '#21ba72',
            ellipse: '#ffffff'
        },
        enabled: {
            bg: '#ced4e0',
            ellipse: '#ffffff'
        }
    },
    Tabs: {
        bgActive: '#21ba72',
        bgSecondary: '#ffffff'
    },
    Text: {
        brand: '#21ba72',
        critical: '#d91419',
        main: '#000000',
        mainInverse: '#ffffff',
        secondary: 'rgba(0, 0, 0, 0.56)',
        secondaryInverse: 'rgba(255, 255, 255, 0.56)',
        success: '#11be1c',
        tertiary: 'rgba(0, 0, 0, 0.4)',
        tertiaryInverse: 'rgba(255, 255, 255, 0.4)',
        warning: '#eb8900'
    },
    TextField: {
        base1: {
            disabled: {
                bg: 'rgba(51, 63, 72, 0.04)'
            },
            enabled: {
                bg: 'rgba(51, 63, 72, 0.08)'
            },
            error: {
                bg: '#ffffff',
                stroke: '#d91419'
            },
            focus: {
                bg: '#ffffff',
                stroke: '#21ba72'
            },
            hover: {
                bg: '#ffffff',
                stroke: 'rgba(0, 0, 0, 0.16)'
            }
        },
        base2: {
            disabled: {
                bg: 'rgba(51, 63, 72, 0.06)'
            },
            enabled: {
                bg: '#ffffff',
                stroke: 'rgba(0, 0, 0, 0.08)'
            }
        },
        error: '#c4c4c4',
        focus: '#c4c4c4',
        hover: '#c4c4c4'
    },
    Tooltip: {
        main: '#c4c4c4'
    }
} 


