/* eslint-disable @typescript-eslint/no-empty-interface */
export interface CustomTheme {}
export interface CustomPaletteColor {}
export interface CustomPaletteColorValues {}
export interface CustomPaletteText {}
export interface CustomPaletteDisabled {}
export interface CustomPaletteBorder {}
export interface CustomPaletteBorderFocus {}
export interface CustomPaletteBackground {}
export interface CustomPaletteBackgroundContainer {}
export interface CustomPalette {}
