// This is autogenerated file, don't try to edit it manually
/* eslint-disable */

export type PaletteColors = {
    Background: {
        blackout: string,
        main: string,
        secondary: string,
        tertiary: string
    },
    Button: {
        contained: {
            critical: {
                enabled: string,
                hover: string,
                press: string
            },
            primary: {
                disabled: string,
                enabled: string,
                hover: string,
                press: string
            },
            secondary: {
                enabled: string,
                hover: string,
                press: string
            }
        },
        outline: {
            critical: {
                bgHover: string,
                bgPress: string,
                strokeEnabled: string
            },
            primary: {
                bgPress: string,
                enabled: string,
                hover: string,
                strokeDisabled: string
            },
            secondary: {
                bgHover: string,
                bgPress: string,
                strokeEnabled: string
            }
        },
        text: {
            critical: {
                bgHover: string,
                bgPress: string
            },
            primary: {
                bgHover: string,
                bgPress: string
            },
            secondary: {
                bgHover: string,
                bgPress: string
            }
        }
    },
    Checkbox: {
        active: {
            bg: string,
            bgHover: string,
            icon: string
        },
        critical: {
            bg: string,
            stroke: string
        },
        disabled: {
            bg: string,
            icon: string
        },
        enabled: {
            bg: string,
            iconHover: string,
            stroke: string,
            strokeHover: string
        }
    },
    ContainerState: {
        focus: string,
        focus2: string,
        focus3: string,
        hover: string,
        press: string
    },
    Datepicker: {
        rangeActive: string,
        rangeFull: string,
        rangeHover: string,
        rangeIn: string,
        rangeOut: string,
        strokeHover: string
    },
    Divider: {
        main: string,
        mainInverse: string,
        secondary: string,
        secondaryInverse: string
    },
    FileUploader: {
        dropzone: {
            strokeDisabled: string,
            strokeEnabled: string,
            strokeError: string,
            strokeHover: string
        },
        file: {
            bgEnabled: string,
            bgError: string
        }
    },
    HintTooltip: {
        bgHint: string,
        bgTooltip: string
    },
    Icon: {
        brand: string,
        critical: string,
        main: string,
        mainInverse: string,
        secondary: string,
        secondaryInverse: string,
        success: string,
        tertiary: string,
        tertiaryInverse: string,
        warning: string
    },
    LabelTag: {
        color1: {
            main: string,
            secondary: string
        },
        color2: {
            main: string,
            secondary: string
        },
        critical: {
            main: string,
            secondary: string
        },
        warning: {
            main: string,
            secondary: string
        }
    },
    RadioButton: {
        active: {
            bg: string
        },
        critical: {
            bg: string
        },
        enabled: {
            bg: string,
            stroke: string
        }
    },
    Shadow: {
        black12: string,
        black4: string,
        black8: string
    },
    Snackbar: {
        bg1: {
            critical: string,
            default: string,
            success: string,
            warning: string
        },
        bg2: {
            critical: string,
            default: string,
            success: string,
            warning: string
        }
    },
    Switcher: {
        active: {
            bg: string,
            ellipse: string
        },
        enabled: {
            bg: string,
            ellipse: string
        }
    },
    Tabs: {
        bgActive: string,
        bgSecondary: string
    },
    Text: {
        brand: string,
        critical: string,
        main: string,
        mainInverse: string,
        secondary: string,
        secondaryInverse: string,
        success: string,
        tertiary: string,
        tertiaryInverse: string,
        warning: string
    },
    TextField: {
        base1: {
            disabled: {
                bg: string
            },
            enabled: {
                bg: string
            },
            error: {
                bg: string,
                stroke: string
            },
            focus: {
                bg: string,
                stroke: string
            },
            hover: {
                bg: string,
                stroke: string
            }
        },
        base2: {
            disabled: {
                bg: string
            },
            enabled: {
                bg: string,
                stroke: string
            }
        },
        error: string,
        focus: string,
        hover: string
    },
    Tooltip: {
        main: string
    }
}

export type Palette = PaletteColors & { type: 'light' | 'dark' }
