name: Assign new issues to organization project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - run: |-
           gh api graphql -F contentId=$ITEM_ID -F projectId=$PROJECT_ID -f query='
             mutation($projectId: ID!, $contentId: ID!) {
               addProjectV2ItemById(input: {projectId: $projectId contentId: $contentId}) {
                 item {
                   id
                 }
             }
           }'
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
          ITEM_ID: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          PROJECT_ID: ${{ secrets.QUARX_PROJECT_ID }}
