name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --production=false

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --production=false
      - run: yarn build

  linter:
    name: Run Linters
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --production=false
      - run: yarn lint

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --production=false
      - run: yarn test