name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/bun.lockb') }}
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - run: bun install --frozen-lockfile

  build:
    name: Run Build
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/bun.lockb') }}
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - run: bun run build

  linter:
    name: Run Linters
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/bun.lockb') }}
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - run: bun run lint:branch

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/bun.lockb') }}
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - run: bun run test
