name: Figma Icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1,4'

permissions:
  pull-requests: write
jobs:
  prepare:
    name: Prepare deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --production=false
      - run: cd ./scripts/figma && yarn install --production=false


  loadIcons:
    name: Load Icons
    runs-on: ubuntu-latest
    needs: [prepare]
    env:
      ICONS_FILE_KEY: ${{ secrets.FIGMA_ICONS_FILE }}
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
      - run: yarn run ci:figma:icons
      - uses: peter-evans/create-pull-request@v4.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: figma/icons-${{ steps.date.outputs.date }}
          commit-message: "figma: Автоматическая выгрузка иконок"
          title: "figma: Автоматическая выгрузка иконок"
          body: "Автоматическая выгрузка иконок из Figma"
