// This is autogenerated file, don't try to edit it manually
/* eslint-disable */

export const typography = {
    Text: {
        L: {
            Medium: {
                fontFamily: 'SB Sans Text',
                fontWeight: 500,
                fontSize: 16,
                letterSpacing: -0.1,
                lineHeight: '24px'
            },
            Regular: {
                fontFamily: 'SB Sans Text',
                fontWeight: 400,
                fontSize: 16,
                letterSpacing: -0.1,
                lineHeight: '24px'
            },
            Semibold: {
                fontFamily: 'SB Sans Text',
                fontWeight: 600,
                fontSize: 16,
                letterSpacing: -0.1,
                lineHeight: '24px'
            }
        },
        M: {
            Medium: {
                fontFamily: 'SB Sans Text',
                fontWeight: 500,
                fontSize: 14,
                lineHeight: '20px'
            },
            Regular: {
                fontFamily: 'SB Sans Text',
                fontWeight: 400,
                fontSize: 14,
                lineHeight: '20px'
            },
            Semibold: {
                fontFamily: 'SB Sans Text',
                fontWeight: 600,
                fontSize: 14,
                lineHeight: '20px'
            }
        },
        S: {
            Medium: {
                fontFamily: 'SB Sans Text',
                fontWeight: 500,
                fontSize: 12,
                letterSpacing: 0.2,
                lineHeight: '16px'
            },
            Regular: {
                fontFamily: 'SB Sans Text',
                fontWeight: 400,
                fontSize: 12,
                letterSpacing: 0.2,
                lineHeight: '16px'
            },
            Semibold: {
                fontFamily: 'SB Sans Text',
                fontWeight: 600,
                fontSize: 12,
                letterSpacing: 0.2,
                lineHeight: '16px'
            }
        },
        XL: {
            Medium: {
                fontFamily: 'SB Sans Text',
                fontWeight: 500,
                fontSize: 20,
                letterSpacing: -0.2,
                lineHeight: '28px'
            },
            Regular: {
                fontFamily: 'SB Sans Text',
                fontWeight: 400,
                fontSize: 20,
                letterSpacing: -0.2,
                lineHeight: '28px'
            },
            Semibold: {
                fontFamily: 'SB Sans Text',
                fontWeight: 600,
                fontSize: 20,
                letterSpacing: -0.2,
                lineHeight: '28px'
            }
        }
    }
} as const

export type Typography = typeof typography;
